theme: jekyll-theme-hacker
title: Hilangin.bg
description: Hilangin.bg adalah aplikasi web yang dapat menghilangkan background foto maupun video. Selain itu akan disediakan fitur untuk menggantikan background dengan template yang telah disediakan dan bisa menambahkan background yang diinginkan. 
